# © 2019 Joseph Cameron - All Rights Reserved
# jfc-smart_handles ci script

dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      env: Build, Test & Deploy
      script:
        - |
          cd workspace
          cmake .. -DCMAKE_CXX_FLAGS="-pedantic -Weverything -Wno-c++98-compat -Wno-padded -Ofast -flto -funroll-loops -m64 -march=native -std=c++17 -stdlib=libc++"
          make
          ctest --extra-verbose
      after_success:
        - |
          cd ..;touch build/${CURRENT_COMMIT_HASH};zip -r ~/${TRAVIS_OS_NAME}.zip build -x build/.keep
          git remote set-url --push origin https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git fetch --all
          git checkout -b gh-pages;git pull origin gh-pages;git clean -fxd;git reset --hard
          mv ~/${TRAVIS_OS_NAME}.zip ./build
          git add ./build/${TRAVIS_OS_NAME}.zip; git commit -m "${TRAVIS_OS_NAME} build for ${CURRENT_COMMIT_HASH}"
          git push --force --set-upstream origin gh-pages

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
      env: Build, Test & Deploy
      script:
        - |
          gcc -v; g++ -v; cmake --version
          cd workspace
          cmake .. -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native"
          make
          ctest --extra-verbose
      after_success:
        - |
          cd ..;touch build/${CURRENT_COMMIT_HASH};zip -r ~/${TRAVIS_OS_NAME}.zip build -x build/.keep
          git remote set-url --push origin https://${GITHUB_PUBLIC_REPO_TOKEN}@$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          git fetch --all
          git checkout -b gh-pages;git pull origin gh-pages;git clean -fxd;git reset --hard
          mv ~/${TRAVIS_OS_NAME}.zip ./build
          git add ./build/${TRAVIS_OS_NAME}.zip; git commit -m "${TRAVIS_OS_NAME} build for ${CURRENT_COMMIT_HASH}"
          git push --force --set-upstream origin gh-pages

before_script: 
  - |
    CURRENT_COMMIT_HASH="$(git rev-parse HEAD)"
 
