# © 2019 Joseph Cameron - All Rights Reserved
# jfc-smart_handles ci script

dist: bionic 
sudo: required
language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      env: Build, Test
      script:
        - |
          cd workspace
          cmake .. -DCMAKE_CXX_FLAGS="-pedantic -Weverything -Wno-c++98-compat -Wno-padded -Ofast -flto -funroll-loops -m64 -march=native -std=c++17 -stdlib=libc++"
          make
          ctest --extra-verbose

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - git
      env: Build, Test
      script:
        - |
          cd workspace
          cmake .. -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Ofast -flto -funroll-loops -m64 -march=native"
          make
          ctest --extra-verbose

    - os: linux
      if: branch = master
      compiler: gcc
      addons:
        apt:
          packages:
            - doxygen
      env: Generate documentation
      script:
        - |
          cd workspace
          cmake .. -DJFC_BUILD_DEMO=OFF -DJFC_BUILD_DOCS=ON -DJFC_BUILD_TESTS=OFF
          mv docs ~
          REMOTE_URL=$(git config --get remote.origin.url | sed -e "s/^https:\/\///")
          cd ~
          git clone --branch=gh-pages "https://${GITHUB_PUBLIC_REPO_TOKEN}@$REMOTE_URL" gh-pages
          cd gh-pages
          mv ~/docs/* .
          git add --all
          git commit -m "updating docs"
          git push
          
    - os: linux
      compiler: gcc
      env: Code Coverage
      before_install: pip install --user cpp-coveralls
      script:
        - |
          cd workspace
          cmake .. -DJFC_BUILD_DOCS=OFF -DCMAKE_CXX_FLAGS="-g -O0 -Wall -fprofile-arcs -ftest-coverage"
          make
          make test
          cd ..
          after_success:
          - |
            #cd ..
            coveralls --exclude cmake workspace



before_script: 
  - |
    CURRENT_COMMIT_HASH="$(git rev-parse HEAD)"

